In [1]:
# library imports:
# mesa
from mesa import Agent, Model
from mesa.datacollection import DataCollector
# load all available schedulers
import mesa.time as time
import math
import random
# matplot lib for plotting, numpy for all sorts of useful math
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# basic python statistics
import statistics as stat

# import pandas
import pandas as pd

# Required libraries for animation
from matplotlib.animation import FuncAnimation
from matplotlib import animation, rc, collections
from IPython.display import HTML

from model import RecyclingModel
from main import RecyclingModel

In [16]:
def run_model():
   model = RecyclingModel()
   number_of_steps = 240
   for i in range(number_of_steps):
      model.step()
   return model.datacollector_waste.get_model_vars_dataframe()

dataframe = run_model()

dataframe

,Waste Rotterdam,Waste Vlaardingen,Waste Schiedam,Recycled plastic waste Rotterdam,Recycled plastic waste Vlaardingen,Recycled plastic waste Schiedam,Percentage recycled Rotterdam,Percentage recycled Vlaardingen,Percentage recycled Schiedam
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,399.737404,202.049975,281.303121,10.044418,5.051214,7.696264,0.025128,0.025000,0.027359
2,397.554822,202.737530,275.715085,9.989566,5.075788,7.508060,0.025128,0.025036,0.027231
3,397.065778,200.431266,273.765540,9.980184,5.026533,7.470181,0.025135,0.025079,0.027287
4,397.694122,195.215838,277.562163,9.957535,4.890091,7.577583,0.025038,0.025050,0.027300
...,...,...,...,...,...,...,...,...,...
236,308.092472,150.217277,215.460688,15.742192,7.723311,12.007087,0.051096,0.051414,0.055728
237,307.070641,153.193722,212.055400,15.741641,7.824729,11.780779,0.051264,0.051077,0.055555
238,308.945460,151.944000,213.971442,15.787223,7.798476,11.921654,0.051100,0.051325,0.055716
239,303.739377,155.136198,211.424732,15.537865,7.949475,11.762585,0.051155,0.051242,0.055635
240,300.298857,150.996329,212.088901,15.389375,7.732387,11.752193,0.051247,0.051209,0.055412

In [17]:
dataframe = dataframe[1:241]

In [18]:
dataframe

,Waste Rotterdam,Waste Vlaardingen,Waste Schiedam,Recycled plastic waste Rotterdam,Recycled plastic waste Vlaardingen,Recycled plastic waste Schiedam,Percentage recycled Rotterdam,Percentage recycled Vlaardingen,Percentage recycled Schiedam
1,399.737404,202.049975,281.303121,10.044418,5.051214,7.696264,0.025128,0.025000,0.027359
2,397.554822,202.737530,275.715085,9.989566,5.075788,7.508060,0.025128,0.025036,0.027231
3,397.065778,200.431266,273.765540,9.980184,5.026533,7.470181,0.025135,0.025079,0.027287
4,397.694122,195.215838,277.562163,9.957535,4.890091,7.577583,0.025038,0.025050,0.027300
5,385.378143,193.648772,266.797796,9.652711,4.860719,7.263465,0.025047,0.025101,0.027225
...,...,...,...,...,...,...,...,...,...
236,308.092472,150.217277,215.460688,15.742192,7.723311,12.007087,0.051096,0.051414,0.055728
237,307.070641,153.193722,212.055400,15.741641,7.824729,11.780779,0.051264,0.051077,0.055555
238,308.945460,151.944000,213.971442,15.787223,7.798476,11.921654,0.051100,0.051325,0.055716
239,303.739377,155.136198,211.424732,15.537865,7.949475,11.762585,0.051155,0.051242,0.055635
240,300.298857,150.996329,212.088901,15.389375,7.732387,11.752193,0.051247,0.051209,0.055412

In [19]:
dataframe["average_cities"] = (dataframe["Percentage recycled Rotterdam"] + dataframe["Percentage recycled Vlaardingen"] + dataframe["Percentage recycled Schiedam"])/3

C:\Users\hp\AppData\Local\Temp/ipykernel_14132/3456375335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe["average_cities"] = (dataframe["Percentage recycled Rotterdam"] + dataframe["Percentage recycled Vlaardingen"] + dataframe["Percentage recycled Schiedam"])/3

In [20]:
dataframe['average_cities'].mean()

0.050882923234276796

In [28]:
iterations = 10
averages = []
for i in range(iterations):
    dataframe = run_model()
    dataframe = dataframe[1:241]
    dataframe["average_cities"] = (dataframe["Percentage recycled Rotterdam"] + dataframe["Percentage recycled Vlaardingen"] + dataframe["Percentage recycled Schiedam"])/3
    averages.append(dataframe['average_cities'].mean())

UnboundLocalError: local variable 'costs_technology' referenced before assignment

In [9]:
len(averages)

100